### ISSUE TITLE
Commit Plz

### ISSUE THREAD

**Issue by angelless** [NexusServer/Lock#1]
Coding with me!

**Comment by LeeHeoJae** [comment]
이벤트가 'cn.nukkit.event.player.PlayerInteractEvent' 에서 'Lock v1.0' 를 지날 수 없습니다: nexus.Lock 에서의 null
15:18:00 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.level.Level.useItemOn(Level.java:1859)
        at cn.nukkit.Player.handleDataPacket(Player.java:2133)
        at cn.nukkit.network.Network.processPackets(Network.java:180)
        at cn.nukkit.network.Network.processBatch(Network.java:156)
        at cn.nukkit.Player.handleDataPacket(Player.java:1902)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:155)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:997)
        at cn.nukkit.Server.tickProcessor(Server.java:800)
        at cn.nukkit.Server.start(Server.java:779)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.NullPointerException
        at nexus.Lock.onTouch(Lock.java:114)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 16 more

I don't know what do I need to fix it
